from pathlib import Path

HEADER = """# Generated by PipelineForge. Review before production use.\nname: Migrated CI\non:\n  push:\n  pull_request:\npermissions:\n  contents: read\n"""

def _steps(item):
    steps=["      - uses: actions/checkout@v4"]
    if item.get('maven'):
        steps += ["      - uses: actions/setup-java@v4\n        with:\n          distribution: temurin\n          java-version: '17'\n          cache: maven", "      - run: mvn -B verify"]
    elif item.get('gradle'):
        steps += ["      - uses: actions/setup-java@v4\n        with:\n          distribution: temurin\n          java-version: '17'\n          cache: gradle", "      - run: chmod +x gradlew && ./gradlew build"]
    elif item.get('node'):
        steps += ["      - uses: actions/setup-node@v4\n        with:\n          node-version: '20'\n          cache: npm", "      - run: npm ci", "      - run: npm test --if-present"]
    elif item.get('python'):
        steps += ["      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.12'\n          cache: pip", "      - run: pip install -r requirements.txt", "      - run: pytest -q"]
    elif item.get('dotnet'):
        steps += ["      - uses: actions/setup-dotnet@v4\n        with:\n          dotnet-version: '8.0.x'", "      - run: dotnet restore", "      - run: dotnet build --no-restore", "      - run: dotnet test --no-build"]
    else:
        steps += ["      - run: echo 'TODO: replace with project-specific build and test steps'"]
    if item.get('docker') or item.get('container'):
        steps += ["      - run: docker build -t migration-validation:${{ github.sha }} ."]
    return steps

def workflow_for(item):
    runner=item.get('runner','ubuntu-latest')
    body=HEADER+f"jobs:\n  build:\n    runs-on: {runner}\n    timeout-minutes: 30\n    steps:\n"+'\n'.join(_steps(item))+'\n'
    return body

def reusable_workflow_for(item):
    tech='generic'
    for key in ('maven','gradle','node','python','dotnet'):
        if item.get(key): tech=key; break
    return f"""# PipelineForge reusable workflow candidate\nname: Reusable {tech} CI\non:\n  workflow_call:\npermissions:\n  contents: read\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n"""+'\n'.join(_steps(item))+'\n'

def generate(items,outdir):
    out=Path(outdir); out.mkdir(parents=True,exist_ok=True); files=[]
    reusable_dir=out/'reusable'; reusable_dir.mkdir(exist_ok=True)
    reusable_seen={}
    for i,x in enumerate(items,1):
        name=(x.get('jenkins_job') or x.get('full_name') or f'job-{i}').replace('/','__').replace(' ','_')+'.yml'
        path=out/name; path.write_text(workflow_for(x),encoding='utf-8'); files.append(str(path))
        rname=x.get('reusable_workflow') or 'reusable-generic.yml'
        if rname not in reusable_seen:
            rpath=reusable_dir/rname; rpath.write_text(reusable_workflow_for(x),encoding='utf-8'); reusable_seen[rname]=str(rpath)
    return files
